version: '3.1'

services:
  bisgate:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/var/www/html/:cached
  db:
    image: mongo:4.0.8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
