apiVersion: v1
kind: Service
metadata:
  name: {{ include "bisgate.fullname" . }}
  labels:
    {{- include "bisgate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "bisgate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
