apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - /bin/sh
                - -c
                - /cron_job.sh;
              env:
                - name: DB_HOST
                  value: {{ .Values.env.dbHost }}
                - name: DB_PORT
                  value: "{{ .Values.env.dbPort }}"
                - name: DB_DATABASE
                  value: {{ .Values.env.dbDatabase }}
                - name: DB_USERNAME
                  value: {{ .Values.env.dbUsername }}
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.mysqlSecret.name }}
                      key: {{ .Values.mysqlSecret.key }}
                - name: MONGO_DB_HOST_NAME
                  value: {{ .Values.env.mongoDBHostName }}
                - name: MONGO_DB_PORT
                  value: "{{ .Values.env.mongoPort }}"
                - name: MONGO_DB_NO_AUTH
                  value: "{{ .Values.env.mongoNoAuth }}"
                - name: MONGO_DB_USER_NAME
                  value: {{ .Values.env.mongoUserName }}
                - name: MONGO_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.mongoSecret.name }}
                      key: {{ .Values.mongoSecret.key }}
                - name: MONGO_DB_DATABASE
                  value: {{ .Values.env.mongoDatabase }}
                - name: REDIS_CONNECT
                  value: "{{ .Values.env.redisConnect }}"
          restartPolicy: Never
